config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only:[:create]

  devise_for :users

  get "up" => "rails/health#show", as: :rails_health_check

  root "welcome#index"

  get "my_portfolio", to: "users#portfolio"

  get "search_stock", to: "stocks#search"

  post '/users/:id/add_ticker', to: 'users#add_ticker', as: 'add_ticker_to_user'

  delete '/users/:id/delete_ticker', to: 'users#delete_ticker', as: 'delete_ticker_from_user'


  post '/users/update_order', to: 'users#update_order'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/stock.rb
class Stock < ApplicationRecord
	has_many :user_stocks
	has_many :users, through: :user_stocks

	validates :ticker, presence: true

	def self.new_lookup(name)
		results = Alphavantage::TimeSeries.search(keywords: name)
		return nil if results.blank?
		ticker = results.first.symbol
		company_name = results.first.name
		stock =  Alphavantage::TimeSeries.new(symbol: ticker).quote
		previous_close = stock.previous_close

		begin
			return @stock = new(ticker: ticker, name: company_name, last_price: previous_close)
		rescue => exception
			return nil
		end
	end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  # serialize :tickers, Array, coder: JSON
  serialize :tickers, type: Array, coder: JSON
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def search
    @user = current_user
    if params[:stock].present?
      stock = params[:stock].upcase
      @stock = StockLookupService.new_lookup(stock)
      if @stock[:status] == 'ERROR'
        flash.now[:alert] = "API call limit reached"
        respond_to do |format|
          format.js { render partial: 'users/results' }
        end
      elsif @stock[:status] == 'NOT_FOUND'
        flash.now[:alert] = "Invalid search term"
        respond_to do |format|
          format.js { render partial: 'users/results' }
        end
      else
        respond_to do |format|
          format.js { render partial: 'users/results' }
        end
      end
    else
      flash.now[:alert] = "Enter a search term"
      respond_to do |format|
        format.js { render partial: 'users/results' }
      end
    end
  end

end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def portfolio
    @tracked_stocks = current_user.tickers
    # tickers = @tracked_stocks.map { |stock| stock.ticker }
    @stocks = StockPriceService.new(@tracked_stocks).call
    @user = current_user
  end

  def add_ticker
    @user = User.find(params[:id])
    ticker = params[:ticker].upcase

    if @user.tickers.include?(ticker)
      flash[:alert] = "#{ticker} is already in your portfolio"
      redirect_to my_portfolio_path and return
    end

    @user.tickers |= [ticker]

    if @user.save
      flash[:notice] = "#{ticker} added successfully"
      redirect_to my_portfolio_path
    else
      flash.now[:alert] = 'Unable to add stock'
      render 'users/portfolio' 
    end
  end

  def delete_ticker
    @user = User.find(params[:id])
    ticker = params[:ticker].upcase
  
    @user.tickers.delete(ticker)
  
    if @user.save
      flash[:notice] = "#{ticker} was successfully removed from your portfolio."
      redirect_to my_portfolio_path
    else
      flash[:alert] = "Unable to remove #{ticker} from your portfolio."
      render 'users/portfolio' 
    end
  end


  def update_order
    current_user.tickers = params[:order]
    if current_user.save
      head :ok
    else
      head :unprocessable_entity
    end
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    def index
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_messages.html.erb
<% if notice %>
  <div class="alert alert-primary alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if flash[:stock_search_error] %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-2">
  <div class="container">
    <%= link_to 'FinanceTracker', root_path, class:"navbar-brand" %>
    <% if current_user %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to 'Home', root_path, class:"nav-link #{'active' if request.path == root_path}" %>
          </li>
          <li class="nav-item">
            <%= link_to 'My Portfolio', my_portfolio_path, class: "nav-link #{'active' if request.path == my_portfolio_path}" %>
          </li>
        </ul>
        <!-- New UL for the Sign out button -->
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= button_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-primary' %>
          </li>
        </ul>
      </div>
    <% end %>
  </div> 
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/sortablejs@1.14.0/sortablejs.min.js"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </div>
  </body>
</html>

app/views/stocks/_list.html.erb
<div class="row mt-3">
  <div class="col-6">
    <table class="table table-striped table-hover table-bordered">
      <thead>
        <tr>
          <th scope="col"></th> <!-- Empty header for the drag handle -->
          <th scope="col">Ticker</th>
          <th scope="col">Price</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody id="stocks-table-body">
        <% @stocks.each do |stock| %>
          <% if stock %>
            <tr>
              <td class="drag-handle">&#x2630;</td> 
              <td><%= stock[:ticker] %></td>
              <td>
                  <%= stock[:last_price] %>
              </td>
              <td>
								<%= form_with url: delete_ticker_from_user_path(id: @user.id, ticker: stock[:ticker]), method: :delete do |form| %>
									<%= form.submit "Remove from Portfolio", class: "btn btn-danger" %>
								<% end %>
							</td>
            </tr>
          <% else %>
            <tr>
              <td colspan="5">Error: Stock info not available. API call limit reached</td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/_result.html.erb
<% if flash[:alert] && flash[:alert].match(/search term|API call limit reached/) %>
  <div class="mt-3">
    <div class="col-5">
      <%= render 'layouts/messages' %>
    </div>
  </div>
<% end %>

<% if @stock && @stock[:status] == 'OK' %>
    <div class="card card-header mt-3 mb-3" style="display: inline-block;">
      <div class="d-flex flex-row align-items-center">
        <div class='mr-2'><strong> Ticker: </strong> <%= @stock[:ticker] %></div>
        <div class='mr-3'><strong> Price: </strong> <%= @stock[:last_price] %></div>
        <% if @user.tickers.include?(@stock[:ticker]) %>
          <%= form_with url: delete_ticker_from_user_path(id: @user.id, ticker: @stock[:ticker]), method: :delete do |form| %>
            <%= form.submit "Remove from Portfolio", class: "btn btn-danger" %>
          <% end %>
        <% else %>  
          <%= form_with url: add_ticker_to_user_path(@user), method: :post do |form| %>
            <%= form.hidden_field :ticker, value: @stock[:ticker] %>
            <%= form.submit "Add to Portfolio", class: "btn btn-success" %>
          <% end %>      
        <% end%>
      </div>
    </div>
<% end %>

app/views/users/_results.js.erb
document.querySelector('#results').innerHTML = '<%= j render 'users/result' %>'

app/views/users/portfolio.html.erb
<h1 class="pb-5 pt-3">My Portfolio</h1>

<h3 class="pl-2"> Search Stocks </h3>

<%= form_with(url: search_stock_path, method: :get, local: false) do |form| %>
  <div class="row">
    <div class="col-7">
      <%= form.text_field :stock, placeholder: "Stock ticker", class: 'col-12 form-control form-control-lg' %>
    </div>
    <div class="col-sm-3 center">
      <%= form.submit "Search", class: 'btn btn-primary btn-lg' %>
    </div>
  </div>
<% end %>

<div id="results">

</div>

<%= render 'users/result' %>

<% if !@tracked_stocks.empty? %>
  <%= render 'stocks/list' %>
<% else %>
  <div class="mt-3 pl-2">
    <h4>You are not tracking any stocks. Search a stock to begin tracking</h4>
  <div>
<% end %>

<!-- format testing block -->
<!--
<div class="card card-header mt-3" style="display: inline-block;">
  <div class="d-flex flex-row align-items-center">
    <div class='mr-2'><strong> Symbol: </strong> Ticker</div>
    <div class='mr-2'><strong> Name: </strong> Name </div>
    <div><strong> Price: </strong> Price </div>
  </div>
</div>
-->

app/views/welcome/index.html.erb
<div class="container mt-4">
  <div class="jumbotron">
    <h1 class="display-4">Welcome to FinanceTracker!</h1>
    <p class="lead">The ultimate platform for personal finance management and investment tracking.</p>
    <hr class="my-4">
    <p>Whether you're a seasoned investor or just starting out, FinanceTracker provides you with the tools and insights you need to monitor your portfolio, track stock performance, and make informed decisions. Our intuitive interface makes it easy to add and manage your investments, set financial goals, and visualize your progress.</p>
    <p>
      Join our community of savvy users and take control of your financial future today with FinanceTracker.
    </p>
    <%= link_to 'Go to Portfolio', my_portfolio_path, class: "btn btn-primary btn-lg mt-3", role: "button" %>
  </div>
</div>